name: CI
on:
 push:
   branches: [ master ]
 pull_request:
   branches: [ master ]

jobs:
 conviso-sca:
    container:
      image: convisoappsec/flowcli
      env:
        FLOW_API_KEY: ${{ secrets.FLOW_API_KEY }}
        FLOW_PROJECT_CODE: 'nRRlRTeg98ZG7SYJ'
    runs-on:
      - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: execute SCA
        run: flow sca run
